services:
  backend:
    image: satishosk/springboot-backend   # ✅ Docker Hub image
    container_name: springboot-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/employee_management
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Satish@@1303

  frontend:
    image: satishosk/react-frontend  # ✅ Docker Hub image
    container_name: react-app
    ports:
      - "3000:80"

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Satish@@1303
      - MYSQL_DATABASE=employee_management
      - MYSQL_PASSWORD=Satish@@1303
    ports:
      - "3307:3306"
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql  # Corrected relative path
