server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/employee_management}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Satish@@1303}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: spring-boot-backend
